credentials:
  users:
    sampleuser:
      password: 'samplepassword'
      privileges:
        - permissions: [ read, write ]
          spaces: [ kv_store, users ]
groups:
  group-001:
    replicasets:
      replicaset-001:
        instances:
          instance-001:
            iproto:
              listen:
              - uri: 'localhost:3301'
app:
  file: 'myapp.lua'
